extends SceneTree

func _init() -> void:
	var errors: PackedStringArray = PackedStringArray()
	var width: int = int(ProjectSettings.get_setting("display/window/size/window_width_override",0))
	var height: int = int(ProjectSettings.get_setting("display/window/size/window_height_override",0))
	var viewport_width: int = int(ProjectSettings.get_setting("display/window/size/viewport_width",0))
	var viewport_height: int = int(ProjectSettings.get_setting("display/window/size/viewport_height",0))
	var rendering_method: String = String(ProjectSettings.get_setting("rendering/renderer/rendering_method",""))
	var windows_driver: String = String(ProjectSettings.get_setting("rendering/rendering_device/driver.windows",""))
	if width != 1920: errors.append("window_width_override deve ser 1920")
	if height != 1080: errors.append("window_height_override deve ser 1080")
	if viewport_width != 960 or viewport_height != 540: errors.append("base lógica deve permanecer 960x540")
	if rendering_method != "mobile": errors.append("renderer PC deve usar Mobile RenderingDevice")
	if windows_driver != "d3d12": errors.append("driver Windows deve ser d3d12")
	if String(ProjectSettings.get_setting("rendering/rendering_device/driver.windows","")) != "d3d12": errors.append("driver Windows deve ser d3d12")
	if not bool(ProjectSettings.get_setting("rendering/rendering_device/fallback_to_vulkan",false)): errors.append("fallback Vulkan deve permanecer habilitado")
	if not bool(ProjectSettings.get_setting("rendering/rendering_device/fallback_to_opengl3",false)): errors.append("fallback OpenGL deve permanecer habilitado")
	var preset_text: String = FileAccess.get_file_as_string("res://export_presets.cfg")
	if not preset_text.contains("Windows Desktop Full HD"): errors.append("preset Windows Desktop Full HD ausente")
	if not preset_text.contains("Cronicas_de_Valedouro_PC_v0.42.exe"): errors.append("caminho do EXE v0.42 ausente")
	var layout = load("res://scripts/cartoon/cartoon_game_layout.gd")
	if layout == null: errors.append("cartoon_game_layout.gd não carregou")
	if errors.is_empty():
		print("cartoon_pc_fullhd_v040: PASS")
		quit(0)
	else:
		for error in errors: push_error(error)
		print("cartoon_pc_fullhd_v040: FAIL")
		quit(1)
